#!/usr/bin/env python3
from __future__ import annotations

import argparse
import concurrent.futures
import pathlib
import re
from dataclasses import dataclass
from io import BytesIO
from typing import Iterable

import requests
import yaml
from PIL import Image, ImageOps


ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / "data" / "webstack.yml"
OVERRIDES_FILE = ROOT / "data" / "telegram_logo_overrides.yml"
LOGOS_DIR = ROOT / "static" / "logos"
THUMBS_DIR = ROOT / "static" / "logos-thumb"

TELEGRAM_URL_RE = re.compile(r"(?i)^https?://(?:t|telegram)\.me/([^/?#]+)")
SKIP_USERNAMES = {"joinchat", "c"}
PLACEHOLDER_LOGOS = {
    "default.webp",
    "/logos/tg.jpg",
    "tg.jpg",
}
GENERIC_SHARED_LOGOS = {
    "/logos/20.jpg",
    "20.jpg",
    "/logos/频道索引_推荐.jpg",
    "频道索引_推荐.jpg",
}
REQUEST_HEADERS = {"User-Agent": "Mozilla/5.0"}
REQUEST_TIMEOUT = 20
JPEG_QUALITY = 92
WEBP_QUALITY = 86
THUMB_SIZE = (80, 80)
MAX_WORKERS = 10


@dataclass(frozen=True)
class Candidate:
    title: str
    username: str
    source_logo: str
    url: str

    @property
    def safe_username(self) -> str:
        return re.sub(r"[^a-z0-9._-]+", "_", self.username.lower())

    @property
    def logo_rel_path(self) -> str:
        return f"/logos/tg-avatar-{self.safe_username}.jpg"

    @property
    def thumb_rel_path(self) -> str:
        return f"/logos-thumb/tg-avatar-{self.safe_username}.jpg.webp"

    @property
    def avatar_url(self) -> str:
        return f"https://t.me/i/userpic/320/{self.username}.jpg"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Download Telegram avatars for placeholder logo entries and generate local overrides."
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=MAX_WORKERS,
        help=f"Concurrent download workers (default: {MAX_WORKERS}).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be generated without writing files.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Return a non-zero exit code when any avatar download fails.",
    )
    return parser.parse_args()


def extract_username(url: str) -> str | None:
    match = TELEGRAM_URL_RE.match(url or "")
    if not match:
        return None

    username = match.group(1)
    lower_username = username.lower()
    if lower_username in SKIP_USERNAMES or username.startswith("+"):
        return None
    return username


def collect_candidates(data: Iterable[dict]) -> list[Candidate]:
    candidates: list[Candidate] = []
    seen_usernames: set[str] = set()

    for section in data:
        for link in section.get("links", []):
            title = str(link.get("title", "") or "")
            source_logo = str(link.get("logo", "") or "")
            url = str(link.get("url", "") or "")
            username = extract_username(url)
            if not username:
                continue

            if source_logo not in PLACEHOLDER_LOGOS and source_logo not in GENERIC_SHARED_LOGOS:
                continue

            key = username.lower()
            if key in seen_usernames:
                continue
            seen_usernames.add(key)
            candidates.append(
                Candidate(
                    title=title,
                    username=username,
                    source_logo=source_logo,
                    url=url,
                )
            )

    return candidates


def download_and_write(candidate: Candidate, dry_run: bool = False) -> tuple[str, str]:
    if dry_run:
        return candidate.username.lower(), candidate.logo_rel_path

    response = requests.get(candidate.avatar_url, headers=REQUEST_HEADERS, timeout=REQUEST_TIMEOUT)
    response.raise_for_status()

    image = Image.open(BytesIO(response.content)).convert("RGB")
    image = ImageOps.exif_transpose(image)

    LOGOS_DIR.mkdir(parents=True, exist_ok=True)
    THUMBS_DIR.mkdir(parents=True, exist_ok=True)

    logo_path = LOGOS_DIR / f"tg-avatar-{candidate.safe_username}.jpg"
    thumb_path = THUMBS_DIR / f"tg-avatar-{candidate.safe_username}.jpg.webp"

    image.save(logo_path, format="JPEG", quality=JPEG_QUALITY, optimize=True)

    resampling = getattr(Image, "Resampling", Image).LANCZOS
    thumb = image.copy()
    thumb.thumbnail(THUMB_SIZE, resampling)
    thumb.save(thumb_path, format="WEBP", quality=WEBP_QUALITY, method=6)

    return candidate.username.lower(), candidate.logo_rel_path


def write_overrides(overrides: dict[str, str], dry_run: bool = False) -> None:
    if dry_run:
        return

    header = "# GENERATED by scripts/sync_telegram_logos.py\n"
    body = yaml.safe_dump(overrides, allow_unicode=True, sort_keys=True)
    OVERRIDES_FILE.write_text(header + body, encoding="utf-8")


def main() -> int:
    args = parse_args()
    data = yaml.safe_load(DATA_FILE.read_text(encoding="utf-8"))
    candidates = collect_candidates(data)

    print(f"Found {len(candidates)} Telegram entries that still rely on placeholder logos.")
    if not candidates:
        write_overrides({}, dry_run=args.dry_run)
        print("No work needed.")
        return 0

    overrides: dict[str, str] = {}
    errors: list[tuple[Candidate, Exception]] = []

    with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, args.workers)) as executor:
        future_map = {
            executor.submit(download_and_write, candidate, args.dry_run): candidate
            for candidate in candidates
        }
        for future in concurrent.futures.as_completed(future_map):
            candidate = future_map[future]
            try:
                username_key, logo_path = future.result()
                overrides[username_key] = logo_path
                print(f"OK {candidate.username:<24} -> {logo_path}")
            except Exception as exc:  # noqa: BLE001
                errors.append((candidate, exc))
                print(f"ERR {candidate.username:<24} -> {exc}")

    write_overrides(overrides, dry_run=args.dry_run)

    print(f"Generated overrides for {len(overrides)} Telegram usernames.")
    if errors:
        print(f"Skipped {len(errors)} entries due to download or image errors.")
        return 1 if args.strict else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
